name: Build and Deploy on Tag Push

on:
  push:
    tags: [ 'v*' ]  # Triggers on any tag starting with 'v'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Modify angular.json
        run: |
          sed -i 's/"outputPath": ".*"/"\outputPath": "docs"/g' angular.json
          echo "angular.json updated successfully!"

      - name: Use Node.js 22
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Build Angular App
        run: npm run build -- --base-href /pronto-soccorso-trentini/

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages # The branch the action should deploy to
          folder: docs # The folder the action should deploy
          token: ${{ secrets.ACCESS_TOKEN }}
